import type { Golfer, PoolEntry, TierConfig } from "./types";

export const sampleGolfers: Golfer[] = [
  { id: 1, name: "Scottie Scheffler", country: "USA", worldRanking: 1, score: -12, scoreDisplay: "-12", today: -4, todayDisplay: "-4", thru: "F", position: "1", rounds: [] },
  { id: 2, name: "Rory McIlroy", country: "NIR", worldRanking: 3, score: -10, scoreDisplay: "-10", today: -3, todayDisplay: "-3", thru: "F", position: "2", rounds: [] },
  { id: 3, name: "Jon Rahm", country: "ESP", worldRanking: 5, score: -8, scoreDisplay: "-8", today: -2, todayDisplay: "-2", thru: "16", position: "3", rounds: [] },
  { id: 4, name: "Brooks Koepka", country: "USA", worldRanking: 8, score: -7, scoreDisplay: "-7", today: -1, todayDisplay: "-1", thru: "F", position: "T4", rounds: [] },
  { id: 5, name: "Collin Morikawa", country: "USA", worldRanking: 4, score: -7, scoreDisplay: "-7", today: -3, todayDisplay: "-3", thru: "F", position: "T4", rounds: [] },
  { id: 6, name: "Ludvig Åberg", country: "SWE", worldRanking: 6, score: -6, scoreDisplay: "-6", today: -2, todayDisplay: "-2", thru: "15", position: "6", rounds: [] },
  { id: 7, name: "Xander Schauffele", country: "USA", worldRanking: 2, score: -5, scoreDisplay: "-5", today: 0, todayDisplay: "E", thru: "F", position: "7", rounds: [] },
  { id: 8, name: "Viktor Hovland", country: "NOR", worldRanking: 12, score: -4, scoreDisplay: "-4", today: -1, todayDisplay: "-1", thru: "F", position: "8", rounds: [] },
  { id: 9, name: "Patrick Cantlay", country: "USA", worldRanking: 9, score: -3, scoreDisplay: "-3", today: 1, todayDisplay: "+1", thru: "F", position: "T9", rounds: [] },
  { id: 10, name: "Bryson DeChambeau", country: "USA", worldRanking: 10, score: -3, scoreDisplay: "-3", today: -2, todayDisplay: "-2", thru: "14", position: "T9", rounds: [] },
  { id: 11, name: "Tommy Fleetwood", country: "ENG", worldRanking: 11, score: -2, scoreDisplay: "-2", today: 0, todayDisplay: "E", thru: "F", position: "11", rounds: [] },
  { id: 12, name: "Hideki Matsuyama", country: "JPN", worldRanking: 7, score: -1, scoreDisplay: "-1", today: 1, todayDisplay: "+1", thru: "F", position: "12", rounds: [] },
  { id: 13, name: "Tony Finau", country: "USA", worldRanking: 15, score: 0, scoreDisplay: "E", today: 2, todayDisplay: "+2", thru: "F", position: "13", rounds: [] },
  { id: 14, name: "Shane Lowry", country: "IRL", worldRanking: 14, score: 1, scoreDisplay: "+1", today: 0, todayDisplay: "E", thru: "F", position: "14", rounds: [] },
  { id: 15, name: "Dustin Johnson", country: "USA", worldRanking: 20, score: 2, scoreDisplay: "+2", today: 1, todayDisplay: "+1", thru: "F", position: "15", rounds: [] },
  { id: 16, name: "Cameron Smith", country: "AUS", worldRanking: 18, score: 3, scoreDisplay: "+3", today: 2, todayDisplay: "+2", thru: "F", position: "16", rounds: [] },
];

export const samplePoolEntries: PoolEntry[] = [
  {
    id: 1,
    name: "Mike Thompson",
    golfers: [sampleGolfers[0], sampleGolfers[2], sampleGolfers[6], sampleGolfers[10]],
    totalPoints: 145,
  },
  {
    id: 2,
    name: "Sarah Chen",
    golfers: [sampleGolfers[1], sampleGolfers[4], sampleGolfers[7], sampleGolfers[11]],
    totalPoints: 132,
  },
  {
    id: 3,
    name: "Jake Wilson",
    golfers: [sampleGolfers[3], sampleGolfers[5], sampleGolfers[8], sampleGolfers[12]],
    totalPoints: 118,
  },
  {
    id: 4,
    name: "Emily Davis",
    golfers: [sampleGolfers[0], sampleGolfers[1], sampleGolfers[9], sampleGolfers[13]],
    totalPoints: 155,
  },
  {
    id: 5,
    name: "Chris Martinez",
    golfers: [sampleGolfers[2], sampleGolfers[6], sampleGolfers[11], sampleGolfers[14]],
    totalPoints: 98,
  },
];

export const tiers: TierConfig[] = [
  {
    tier: 1,
    name: "Tier 1",
    picks: 2,
    players: [
      { id: 101, name: "Scottie Scheffler", country: "USA" },
      { id: 102, name: "Jon Rahm", country: "ESP" },
      { id: 103, name: "Rory McIlroy", country: "NIR" },
      { id: 104, name: "Bryson DeChambeau", country: "USA" },
      { id: 105, name: "Ludvig Åberg", country: "SWE" },
      { id: 106, name: "Xander Schauffele", country: "USA" },
      { id: 107, name: "Cameron Young", country: "USA" },
      { id: 108, name: "Tommy Fleetwood", country: "ENG" },
      { id: 109, name: "Matt Fitzpatrick", country: "ENG" },
      { id: 110, name: "Collin Morikawa", country: "USA" },
    ],
  },
  {
    tier: 2,
    name: "Tier 2",
    picks: 2,
    players: [
      { id: 201, name: "Justin Rose", country: "ENG" },
      { id: 202, name: "Brooks Koepka", country: "USA" },
      { id: 203, name: "Jordan Spieth", country: "USA" },
      { id: 204, name: "Hideki Matsuyama", country: "JPN" },
      { id: 205, name: "Robert MacIntyre", country: "SCO" },
      { id: 206, name: "Russell Henley", country: "USA" },
      { id: 207, name: "Chris Gotterup", country: "USA" },
      { id: 208, name: "Patrick Reed", country: "USA" },
      { id: 209, name: "Viktor Hovland", country: "NOR" },
      { id: 210, name: "Si Woo Kim", country: "KOR" },
    ],
  },
  {
    tier: 3,
    name: "Tier 3",
    picks: 1,
    players: [
      { id: 301, name: "Min Woo Lee", country: "AUS" },
      { id: 302, name: "Justin Thomas", country: "USA" },
      { id: 303, name: "Patrick Cantlay", country: "USA" },
      { id: 304, name: "Adam Scott", country: "AUS" },
      { id: 305, name: "Akshay Bhatia", country: "USA" },
      { id: 306, name: "Sepp Straka", country: "AUT" },
      { id: 307, name: "Jake Knapp", country: "USA" },
      { id: 308, name: "Jason Day", country: "AUS" },
      { id: 309, name: "Tyrrell Hatton", country: "ENG" },
      { id: 310, name: "Shane Lowry", country: "IRL" },
    ],
  },
  {
    tier: 4,
    name: "Tier 4",
    picks: 1,
    players: [
      { id: 401, name: "Sam Burns", country: "USA" },
      { id: 402, name: "Corey Conners", country: "CAN" },
      { id: 403, name: "Nicolai Højgaard", country: "DEN" },
      { id: 404, name: "J.J. Spaun", country: "USA" },
      { id: 405, name: "Kurt Kitayama", country: "USA" },
      { id: 406, name: "Jacob Bridgeman", country: "USA" },
      { id: 407, name: "Maverick McNealy", country: "USA" },
      { id: 408, name: "Cameron Smith", country: "AUS" },
      { id: 409, name: "Matt McCarty", country: "USA" },
      { id: 410, name: "Harris English", country: "USA" },
    ],
  },
  {
    tier: 5,
    name: "Tier 5",
    picks: 1,
    players: [
      { id: 501, name: "Daniel Berger", country: "USA" },
      { id: 502, name: "Keegan Bradley", country: "USA" },
      { id: 503, name: "Michael Brennan", country: "USA" },
      { id: 504, name: "Ángel Cabrera", country: "ARG" },
      { id: 505, name: "Brian Campbell", country: "USA" },
      { id: 506, name: "Wyndham Clark", country: "USA" },
      { id: 507, name: "Fred Couples", country: "USA" },
      { id: 508, name: "Nicolas Echavarria", country: "COL" },
      { id: 509, name: "Ethan Fang", country: "USA" },
      { id: 510, name: "Ryan Fox", country: "NZL" },
      { id: 511, name: "Sergio García", country: "ESP" },
      { id: 512, name: "Ryan Gerard", country: "USA" },
      { id: 513, name: "Max Greyserman", country: "USA" },
      { id: 514, name: "Ben Griffin", country: "USA" },
      { id: 515, name: "Harry Hall", country: "ENG" },
      { id: 516, name: "Brian Harman", country: "USA" },
      { id: 517, name: "Jackson Herrington", country: "USA" },
      { id: 518, name: "Rasmus Højgaard", country: "DEN" },
      { id: 519, name: "Brandon Holtz", country: "USA" },
      { id: 520, name: "Max Homa", country: "USA" },
      { id: 521, name: "Mason Howell", country: "USA" },
      { id: 522, name: "Sungjae Im", country: "KOR" },
      { id: 523, name: "Casey Jarvis", country: "RSA" },
      { id: 524, name: "Dustin Johnson", country: "USA" },
      { id: 525, name: "Zach Johnson", country: "USA" },
      { id: 526, name: "Naoyuki Kataoka", country: "JPN" },
      { id: 527, name: "John Keefer", country: "USA" },
      { id: 528, name: "Michael Kim", country: "USA" },
      { id: 529, name: "Fifa Laopakdee", country: "THA" },
      { id: 530, name: "Haotong Li", country: "CHN" },
      { id: 531, name: "Tom McKibbin", country: "NIR" },
      { id: 532, name: "Rasmus Neergaard-Petersen", country: "DEN" },
      { id: 533, name: "Alex Noren", country: "SWE" },
      { id: 534, name: "Andrew Novak", country: "USA" },
      { id: 535, name: "José María Olazábal", country: "ESP" },
      { id: 536, name: "Carlos Ortiz", country: "MEX" },
      { id: 537, name: "Marco Penge", country: "ENG" },
      { id: 538, name: "Aldrich Potgieter", country: "RSA" },
      { id: 539, name: "Mateo Pulcini", country: "ARG" },
      { id: 540, name: "Aaron Rai", country: "ENG" },
      { id: 541, name: "Kristoffer Reitan", country: "NOR" },
      { id: 542, name: "Davis Riley", country: "USA" },
      { id: 543, name: "Charl Schwartzel", country: "RSA" },
      { id: 544, name: "Vijay Singh", country: "FIJ" },
      { id: 545, name: "Samuel Stevens", country: "USA" },
      { id: 546, name: "Nick Taylor", country: "CAN" },
      { id: 547, name: "Sami Valimaki", country: "FIN" },
      { id: 548, name: "Bubba Watson", country: "USA" },
      { id: 549, name: "Mike Weir", country: "CAN" },
      { id: 550, name: "Danny Willett", country: "ENG" },
      { id: 551, name: "Gary Woodland", country: "USA" },
      { id: 998, name: "Will Zalatoris", country: "USA"},
      { id: 999, name: "Tony Finau", country: "USA"}
    ],
  },
];
